### ISSUE TITLE
Kotlin 1.6.X support

### ISSUE THREAD

**Issue by fodeguirassy** [KaustubhPatange/AutoBindings#2]
After upgraded project kotlin version to `1.6.21`, build fails. 

Can you help ? 

![Capture d’écran 2022-10-27 à 16 45 37](https://user-images.githubusercontent.com/16901741/198323413-fa1c68b6-7530-403c-a1b3-44fa82759513.png)

**Comment by KaustubhPatange** [comment]
Sorry to say, but this project is not maintained anymore. You can easily create an abstract class to encapsulate all serialization & deserialization logic.
